### ISSUE TITLE
work with lambda?

### ISSUE THREAD

**Issue by nabaz** [zibasec/django-saml2-pro-auth#29]
can be use for server-less app? api gateway +  lambda?

**Comment by defionscode** [comment]
I'm not sure that you should be trying to run Django on lambda to begin
with.

**Comment by nabaz** [comment]
I have couple of apps (django) running on lambda and the statics hosted on s3 And they all working perfectly fine, not sure what’s the reason not to? (i get not all packages are available for lambda)

Thanks!
Nabaz Maaruf

**Comment by defionscode** [comment]
Hmm interesting. I'm not sure if it would work, if you feel like trying it
and letting me know that would be cool.
