### ISSUE TITLE
Add example usage to repo and update docs

### ISSUE THREAD

**Issue by 1oglop1** [zibasec/django-saml2-pro-auth#4]
Hi, 
first of all I'd like to thank you for great work.

Do you have any simple example how to use this in app? I have really basic experience with Django and I'd like to use this.

Thank you

**Comment by defionscode** [comment]
hmm not currently no but I would like to. I'm contemplating just making an okta developer account and providing a demo for that. I'll leave this open as I think it's important to have this

**Comment by 1oglop1** [comment]
Okay, I will try to work on this myself and consult it here if you don't mind.
And open-source my example once it's done.

**Comment by defionscode** [comment]
sure thing

**Comment by shepdelacreme** [comment]
Fixed in #38
